### ISSUE TITLE
Allow specification of python executable for cmake while manually compiling & installing

### ISSUE THREAD

**Issue by WillemWybo** [nest/nest-simulator#1560]
**Is your feature request related to a problem? Please describe.**
It seems that the `-Dwith-python=3` option for `cmake` command can not find the name `python3`, nor the explicit path to the python executable.

Tried installing with something like
```cmake -Dwith-python=3 -DCMAKE_INSTALL_PREFIX:PATH=</install/path> </path/to/NEST/src>```
as per [https://nest-simulator.readthedocs.io/en/stable/installation/linux_install.html](url) 

**Describe the solution you'd like**
Allow specifying which python executable to use

**Describe alternatives you've considered**
Had to assign the alias `python` to `python3` to install successfully.

**Comment by clinssen** [comment]
Hi, thanks for your report. We just merged a PR that sunsets Python 2 support. This changed the semantics of the "with-python" parameter slightly, so any further testing should be on the latest master branch.

In any case, your issue sounds more like a CMake issue, because we rely on it to locate Python: https://github.com/nest/nest-simulator/blob/7361bada6cd40a23140e976ec899fb7037cb7146/cmake/ProcessOptions.cmake#L401

Note that there are some marginally documented CMake parameters such as ``PYTHON_EXECUTABLE`` and ``PYTHON_LIBRARY``; see https://nest-simulator.readthedocs.io/en/stable/installation/install_options.html#python3-binding-pynest. Could you try if these solve your problem without manually aliasing python to python3?

**Comment by gtrensch** [comment]
If following @clinssen's advice doesn't solve the problem, can you please provide the CMake output?

**Comment by WillemWybo** [comment]
Just ran CMake on the master branch and it seems to be working now (without the `-Dwith-python=3` option, guess that's the default now?)

**Comment by gtrensch** [comment]
@WillemWybo, Python 2.x is no longer supported and therefore we only allow `-Dwith-python=[OFF|ON]`. Yes, running with `-Dwith-python=ON` (Python 3) is the default now. See also [INSTALL](https://github.com/nest/nest-simulator/blob/master/INSTALL).

**Comment by terhorstd** [comment]
This seems to be solved.
