### ISSUE TITLE
NEST module generated from NESTML fails to build on macOS when NEST is installed from conda-forge

### ISSUE THREAD

**Issue by pnbabu** [nest/nest-simulator#2497]
**Describe the bug**
After installing NEST through `conda-forge` and installing NESTML via `pip` in the same conda environment, the generated NEST module from NESTML fails to compile on macOS with the following error:

```
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make[2]: *** [CMakeFiles/nestmlmodule_lib.dir/nestmlmodule.o] Error 1
make[1]: *** [CMakeFiles/nestmlmodule_lib.dir/all] Error 2
make: *** [all] Error 2
```

**To Reproduce**
Steps to reproduce the behavior: https://nestml.readthedocs.io/en/latest/installation.html#anaconda-installation

```
conda create --name nestml_conda
conda activate nestml_conda
conda install -c conda-forge nest-simulator ipython cxx-compiler pyqt wxpython
pip install nestml --upgrade
```
The `C++` path and the `$PYTHONPATH` are updated as mentioned in the above link. Then running the below command gives the compilation error.

```
nestml --input_path models/neurons/iaf_psc_exp.nestml --target_path target_iaf --logging_level INFO
```

**Desktop/Environment (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Python-Version: Python 3.10
 - NEST-Version: 3.3
 - Installation: NEST installed through conda-forge

**Additional context**
I suspect the error is because `$HOME/miniconda3/envs/nestml_conda/lib/libomp.dylib` is not linked during the compilation. The library is also not listed under `$HOME/miniconda3/envs/nestml_conda/bin/nest-config --libs`. Although, manually adding it to the `nest-config` file doesn't resolve the error.

**Comment by heplesser** [comment]
The problem is that `nest-config --libs` from the `conda-forge` build returns `... -fopenmp=libomp ...`, while it should contain `...  -Xclang -fopenmp ...`. If NEST 3.3 is built locally with clang, this works out. There are some other problems with the libs provide, which have been fixed by #2468 (not available via conda yet).

@steffengraber Is it possible to get the output from the `cmake` run for the conda builds? Maybe that can help to find out why we get the wrong flags.

**Comment by steffengraber** [comment]
Here are the complete build logs for osx_64 and osx_arm64:

osx_64 python3.10
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/566950/logs/50

osx_arm64 python3.10
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/566950/logs/49

**Comment by heplesser** [comment]
Should disappear with wheel-based installation.

**Comment by steffengraber** [comment]
II hope the problem will be solved with the conda package for NEST 3.4.

**Comment by terhorstd** [comment]
Did the 3.4_rc1 solve this?

**Comment by steffengraber** [comment]
It is hard for me to test this in macOS. With the new version, the compiler is added to the run environment and the path inside nest-config is overwritten. This should fix the problem, also in macOS.

**Comment by nicolossus** [comment]
I did a conda installation of 3.4_rc1 on macOS, and the NESTML model still fails to compile with the same error:

```
clang: error: unsupported argument 'libomp' to option 'fopenmp='
make[2]: *** [CMakeFiles/nestmlmodule_module.dir/build.make:76: CMakeFiles/nestmlmodule_module.dir/nestmlmodule.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/nestmlmodule_module.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

However, if I change `-fopenmp=libomp` to `-Xclang -fopenmp` under both `--cflags` and `--libs` in the `nest-config` file, the NESTML model compiles successfully.

The NESTML documentation on Anaconda installation (https://nestml.readthedocs.io/en/latest/installation.html#anaconda-installation) already says one has to:

> Edit `nest-config` and correct the entry under `--compiler` with the output returned by `which c++`

Perhaps a temporary workaround could be for the documentation to instruct macOS users to also replace `-fopenmp=libomp` with `-Xclang -fopenmp` in the `nest-config`.

#### Steps to reproduce:

Download 3.4_rc1 feedstock build [conda_artifacts_20230213.5.1_osx_64_python3.10.____cpython](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=657707&view=artifacts&type=publishedArtifacts) and unpack the file and the archive directory within (I also renamed the archive directory of this particular file to `build_artifacts`).

Create conda environment and install:

```
conda create -n nestml_conda python=3.10
conda install -c conda-forge c-compiler compilers cxx-compiler make cmake zlib boost cython gsl libtool matplotlib-base readline ipython scipy statsmodels openssh pyqt wxpython
conda install --use-local build_artifacts/osx-64/nest-simulator-3.4_rc1-py310h69b982f_0.conda
pip install nestml --upgrade
```

Then replace `--compiler` entry in `~/opt/anaconda3/envs/nestml_conda/bin/nest-config` with output from `which c++` and `-fopenmp=libomp` to `-Xclang -fopenmp` under `--cflags` and `--libs`.

Finally, compile the NESTML model from the NESTML source directory:

    $ nestml --input_path models/neurons/iaf_psc_exp.nestml --target_path target_iaf --logging_level INFO

**Comment by steffengraber** [comment]
@pnbabu Can the issue be closed?

**Comment by pnbabu** [comment]
@steffengraber Yes, it can be closed.
