### ISSUE TITLE
nest as a SPEC CPU benchmark

### ISSUE THREAD

**Issue by heshpdx** [nest/nest-simulator#3217]
Hello friends,

I’m a CPU architect at Ampere Computing where I do performance analysis and workload characterization. I also serve on the [SPEC CPU](https://spec.org/cpu2017/) committee, working on benchmarks for the next version of SPEC CPU, [CPUv8](https://spec.org/cpuv8/) . We try to find computationally intensive workloads in diverse fields, to help measure performance across a wide variety of behaviors and application domains. Based on the longevity of nest, its large active community in biology and its use in education, I have proposed the nest neural network model be included in the next set of marquee benchmarks in SPEC CPU. 

As part of the effort, we have ported and integrated the nest mainline code into the SPEC CPU harness so that it can be tested on a wide variety of systems in a controlled environment to produce reproducible results. We have even built it on native Windows using MSVC and the Intel compiler for Windows – we are happy to share the changes if someone is interested in testing and integrating it back into the upstream mainline for the benefit of the community.

The piece we need help with is an understanding of the multithreaded workloads. Right now, we have *single-threaded* nest command lines which run and produce verifiable output across many compilers (llvm, gcc, icc, aocc, nvhpc, cray), ISAs (aarch64, x86, power) and operating systems (linux, windows, android). We verify the run via checking the .dat files which come out of the simulation runs to make sure that there are no differences in the resulting output. A problem arises when we run with multiple threads, since there are a different number of files produced, and I am unfamiliar with how to coalesce them to verify.

First some fundamental questions: Does a nest invocation with 8 threads perform the same amount of work as a run with 16 threads? Or is it that the problem being solved is larger? If it is the same, how can we verify that?  Does this answer change based on the .sli script used?

In the example below, if I run `examples/nest/brunel-2000_newconnect_dc.sli` (with a small edit to make it run longer)... I tried with 8 threads and 16. It looks like I am simulating the same number of Neurons and Synapses. The 8-thread version outputs 16 files and the 16-threaded version outputs 24 files. The total lines in the files are close. Do they fundamentally contain the same information, just at different sample points?

```
$ ./nest_s_base.O3-64 --userargs=threads=8 brunel-2000_newconnect_dc_LONG.sli
NEST 3.5.0-post0.dev0 (C) 2004 The NEST Initiative
Configuring neuron parameters.
Creating the network.
Configuring neuron parameters.
Creating excitatory spike recorder.
Creating inhibitory spike recorder.
Connecting excitatory neurons.
Connecting inhibitory population.
Connecting spike recorders.
Starting simulation.

Brunel Network Simulation
Number of Threads : 8
Number of Neurons : 95000
Number of Synapses: 902500100
       Excitatory : 722000000
       Inhibitory : 180500000
Excitatory rate   : 6.99 Hz
Inhibitory rate   : 6.825 Hz
Building time     : 23.76 s
Simulation time   : 448.07 s
```

```
$ ls -l brunel-2-in-threaded-95002-* | wc -l
16

$ wc -l brunel-2-in-threaded-95002-* | tail -1
 2811 total
```

```
$ ./nest_s_base.O3-64 --userargs=threads=16 brunel-2000_newconnect_dc_LONG.sli
NEST 3.5.0-post0.dev0 (C) 2004 The NEST Initiative
Configuring neuron parameters.
Creating the network.
Configuring neuron parameters.
Creating excitatory spike recorder.
Creating inhibitory spike recorder.
Connecting excitatory neurons.
Connecting inhibitory population.
Connecting spike recorders.
Starting simulation.

Brunel Network Simulation
Number of Threads : 16
Number of Neurons : 95000
Number of Synapses: 902500100
       Excitatory : 722000000
       Inhibitory : 180500000
Excitatory rate   : 6.985 Hz
Inhibitory rate   : 7.36 Hz
Building time     : 35.39 s
Simulation time   : 332.74 s
```

```
$ ls -l brunel-2-in-threaded-95002-* | wc -l
24

$ wc -l brunel-2-in-threaded-95002-* | tail -1
 2909 total
```

Overall, the goal is to be able to verify that the same amount of work was completed between these two command lines, and verify that they calculated the same result. This allows a benchmark to run on systems with a varying number of hardware cores, so we can measure CPU performance between them. We are allowed to provide some tolerance, in case there is floating point rounding error.

For the multithreaded benchmark, I am exercising the scripts below. The goal is to showcase scalable threading performance, as well as cover a  variety of behaviors in the nest simulator. 
```
brunel-2000_newconnect_dc_LONG.sli
brunel_ps_LONG.sli
hpc_benchmark.sli
microcircuit.sli
```

If you have feedback on which are more or less useful as multithreaded benchmarks, please share your thoughts!

Thank you!

**Comment by heplesser** [comment]
Hello Mahesh!

We are very excited that you have proposed NEST for inclusion in the SPEC CPUv8 benchmark suite! We would be happy to work with you to make this happen. I will answer your more specific questions below.

One important point about NEST (and other neuronal network simulators) is that you can run a wide range of neuronal network models on the NEST simulator, constructing the networks either through SLI or through Python scripts. And if networks are defined in the PyNN specification language, they can be executed on a range of neuronal network simulators, including some neuromorphic systems. Therefore, there isn't "the nest neural network model". The advantage of this is that one can configure networks that are suitable for benchmarking.

In our own work, we have mainly used the `hpc_benchmark.sli` and the `microcircuit.sli` benchmarks. The latter has become a reference benchmark also for neuromorphic and GPU-based simulators (I will post references later).

Concerning the specific Brunel-benchmark you used: Increasing the number of threads will distribute the same workload across more threads, i.e., strong scaling. 

I am a bit confused by the number of output files you report. When running with eight threads, I would expect eight `brunel-2-ex-threaded-...` and eight `brunel-2-ex-threaded-...` files, and with 16 threads correspodingly 16 `ex` and 16 `in` files. Could you double check that?

I noticed that you used a `NEST 3.5.0-post0.dev0` version from Github. We made some substantial improvements in threaded scaling in NEST 3.6, so I would strongly suggest that you update to at least NEST 3.6, ideally to NEST 3.7. With NEST 3.6, we see excellent scaling for the "microcircuit" benchmark up to 128 threads on dual AMD Epyc Rome systems.

Best, Hans Ekkehard

**Comment by heshpdx** [comment]
Thanks for responding, Hans!

I had a feeling you would ask me to rebase, so I attempted that three-way merge right after I posted above.  The SPEC CPU harness builds applications in a totally different manner, so the process of adding a benchmark requires taking humpty-dumpty apart and putting him back together. Something may have gotten lost in that process, because after my merge, I get this runtime error immedately:
```
$ ./nest_r_base.O3-64 

sli-init Fatal []: 
    While executing module initializer: {(nest-init) run}

load Error []: UndefinedName

Start Error []: 
    Something went wrong during initialization of NEST or one of its modules. 
    Probably there is a bug in the startup scripts. Please report the output 
    of NEST at https://github.com/nest/nest-simulator/issues . You can try to 
    find the bug by starting NEST with the option --debug

Start Error []: 
    Something went wrong during initialization of NEST or one of its modules. 
    Probably there is a bug in the startup scripts. Please report the output 
    of NEST at https://github.com/nest/nest-simulator/issues . You can try to 
    find the bug by starting NEST with the option --debug
```
Here is the output from `./nest --debug`: [debug.log](https://github.com/user-attachments/files/15756518/debug.log)

Can you provide some hints as to what I should look at? I am building all the modules as well as `models/models.cpp` and `models/modelsmodule.cpp`.  Is there a config or other flag I should be aware of?

**Comment by heshpdx** [comment]
On the topic of workloads, thank you for the feedback on the benchmark scripts. 

> When running with eight threads, I would expect eight brunel-2-ex-threaded-... and eight brunel-2-ex-threaded-... files, and with 16 threads correspodingly 16 ex and 16 in files. Could you double check that?

Indeed, you are correct! I counted wrong, sorry about that. So the question is, how can I use those files to prove the same work occurred between the two runs, and check that they both came to the "correct answer"? SPEC CPU benchmarks need to scale from 1 thread to N threads, and verify the results are the same using any N.  This is the challenge in front of us.

For the single-threaded benchmark, I am using these scripts which seem to work well. Are they ok?
```
cuba_stdp.sli
structural_plasticity_benchmark.sli
ArtificialSynchrony.sli
```

**Comment by heshpdx** [comment]
Ahoy! Sometimes crafting a detailed message to the author is all that is required to solve one's problem. In making the debug.log and looking at the first line of the output, I realized that I had forgotten to update the `nest/sli/sli-init.sli` and other runtime files to your latest mainline. I did that and the program was able to run again!  I will work on testing all my cmdlines with my 3.7 rebase. Thanks!

**Comment by heshpdx** [comment]
Regarding `microcircuit.sli`, we noticed that there is a bug if we try to run with more than 63 threads. It has something to do with a file not being able to be created. We got around that issue by capping the max thread count in that script. Is this a known limitation?

```
diff -u Potjans_2014/microcircuit.sli ~/867.nest_s/data/refspeed/input/microcircuit.sli
--- Potjans_2014/microcircuit.sli     2024-06-07 16:31:55.464111605 +0000
+++ ~/867.nest_s/data/refspeed/input/microcircuit.sli   2024-05-10 16:28:22.329645268 +0000
@@ -137,6 +137,14 @@
 
 } def
 
+% This model only supports up to 63-way concurrency
+/maxthreads 63 def
+/Truncate63
+{
+  dup maxthreads gt {
+     pop maxthreads
+  } if
+} def
 
 % PrepareSimulation - Set kernel parameters and RNG seeds based on the
 % settings in sim_params.sli.
@@ -148,9 +156,9 @@
     % set global kernel parameters
     <<
        /resolution dt
-       /total_num_virtual_procs n_vp
+       /local_num_threads local_num_threads Truncate63
+       /total_num_virtual_procs n_vp Truncate63
        /overwrite_files overwrite_existing_files
        /rng_seed rng_seed
        output_path (.) neq {
            /data_path output_path
        } if
```

**Comment by heplesser** [comment]
@heshpdx NEST creates a separate spike recorder instance for each thread to allow non-blocking recording and each of these instances opens a separate file. Thus, the `brunel....sli` script running on 64 threads would open 128 output files. Could it be that you hit an operating system limit on the number of open files per process?

I presume that with SPEC CPU you want to test CPU performance rather than I/O system performance. If this is indeed the case, I would suggest to drop the spike time recording to file. This would solve the problem with limited numbers of files. If SPEC rules should allow you to do one run with some form of recording of spikes and another run without it, one could use the following approach: Perform a run with spike recorders in which the spikes are recorded to memory. After then simulation time is up, extract spike data from the spike recorder in the SLI script and write it to file. This only requires one file per process instead of one per thread. Also, read out the spike counter in NEST. Then turn off spike recording completely and re-run the simulation. Read out the spike counter (it is always active) and you should get exactly the same number of spikes as when recording. I can send you code to do this.

When simulating the same network with different numbers of threads, you will obtain results that differ in detail, since the random number sequences in NEST are thread-specific. We have developed several measures to verify that simulations do produce statistically consistent results, see the paper by Gutzen et al below. If you positively need identical results independent of the number of threads used, we can develop a work-around for that.

For strong-scaling experiments, I would encourage you to use the microcircuit model, as it is currently the most widely used network model used for benchmarking, see the paper by Kurth et al below. That paper also gives a rather recent description of the state of the art, although NEST 3.6 and later now outperform NEST 2.14 that was used in that paper. 

Concerning a single-thread benchmark, what are the constraints on running a single benchmark? On my MacBook with Core i5, hpc_benchmark.sli takes in total about two minutes for a single run. If that is acceptable, I would suggest using hpc_benchmark.

**Comment by heplesser** [comment]
And here the promised references:
- Gutzen, R., Von Papen, M., Trensch, G., Quaglio, P., Grün, S., & Denker, M. (2018). Reproducible Neural Network Simulations: Statistical Methods for Model Validation on the Level of Network Activity Data. Frontiers in Neuroinformatics, 12, 90. https://doi.org/10.3389/fninf.2018.00090
- Kurth, A. C., Senk, J., Terhorst, D., Finnerty, J., & Diesmann, M. (2022). Sub-realtime simulation of a neuronal network of natural density. Neuromorphic Computing and Engineering, 2(2), 021001. https://doi.org/10.1088/2634-4386/ac55fc

**Comment by heshpdx** [comment]
Regarding exact answers - we do allow some tolerance based on floating point rounding. If there is a lot of randomness, we can try to reduce that via more deterministic randomness. I've seen that in many benchmark candidates, less (or zero) randomness still provides valid answers and doesn't detract from creating a benchmark representative of the application behavior in the field.

With my latest rebase I still get issues with running Potjans_2014/microcircuit.sli with more than 63 threads (in the SPEC CPU harness):
```
$ ./nest_s_base.O3-64 --userargs=threads=80 microcircuit.sli
NEST 3.7.0-post0.dev0 (C) 2004 The NEST Initiative

SimulationManager::set_status Info []: 
    Temporal resolution changed from 0.1 to 0.1 ms.

NodeManager::prepare_nodes Info []: 
    Preparing 79729 nodes for simulation.

RecordingBackendASCII::prepare() Error []: 
    I/O error while opening file 'spikes_3_0-74246-63.dat'.

Simulate_d Error []: IOError
```
I have enough file descriptors:
```
$ ulimit -Sn
1024
$ ulimit -Hn
1048576
```

I played around with the mainline nest build, and realized the issue is not with threads, but with `/total_num_virtual_procs`.  I was able to recreate the problem on the mainline by increasing Potjans_2014/microcircuit.sli's `/total_num_virtual_procs` to be 80 and it fails the same way as above.  Can you share the correct way to scale up the parallelism in microcircuit.sli? What is your cmdline and how would should I set the parallelism to 32, and to 80?

**Comment by heplesser** [comment]
I had another look at `microcircuit.sli` and it creates a lot of files. The model consists of four cortical layers with two populations each, i.e., a total of eight populations. For each population, the script creates one spike recorder and one voltmeter, thus a total of 16 recording devices (implemented like this because it makes analysis easier later as one does not need to split data into populations later). Each of these devices is replicated once per thread, so for 64 threads you would get 1024 files, for 80 threads 1280 and thus hit your soft limit for file descriptors. To turn this off, open `sim_param.sli` and set the three variables `/save_...` to `false` (around line 92). Spikes will then be stored in memory and no files should be opened.

Concerning setting the number of threads, I am surprised that `--userargs=threads=80` had an effect. Did you make some changes to `microcircuit.sli` to make this work? Since NEST combines MPI- and thread-based parallelization, we have
- the number of MPI ranks M
- the number of threads T per rank
- the number of virtual processes N_VP = M * T

M is defined via mpirun. Inside a NEST script you can either set T through the parameter `local_num_threads` or N_VP through the parameter `total_num_virtual_procs`, which must be divisible by M. Since you work with M=1 only, both approaches are equivalent and you can stick with setting `total_num_virtual_procs` as is used `microcircuit.sli`. NEST guarantees that one gets identical results for fixed N_VP, no matter how it is split between M and T.

The set of files in `Potjans_2014` assumes that parameters are modified in `sim_params.sli` and `network_params.sli`,  respectively, but I assume that for your purposes, you prefer to set parameters on the command line?

One more question: We are mostly using Python scripts in our benchmarking now. Would that be feasible for your benchmarks as well or does that introduce to many confounding factors so that you would want to avoid Python?

**Comment by heshpdx** [comment]
Oh yes, I did change `microcircuit.sli`. In the SPEC CPU harness, a variable is passed down indicating how many threads to use. So I need to employ that on a command line, and that is the amount of parallelism that will be requested. I didn't know the difference between threads per rank and virtual processors. For us, we get one invocation of the command line, and that one process can only spawn up to N threads. MPI is not used, python is not used. This is all C++ and cmdline, which is why the sli scripts work so well. OpenMP is also allowed, but I opted to throw in the `threads` variable along the cmdline and modify the scripts to support it, or so I thought!  Getting python inside the harness is difficult or impossible, so I would prefer not to change now. We are already have things working very well with the sli. So one thing you can help with is to craft the Potjans scripts in the proper way, so it could run in the harness with N threads specified on the cmdline. Is that possible?  I can use that solution to make sure I am doing the right thing for hpc_benchmark. Thanks!

**Comment by heplesser** [comment]
Thanks for the explanations. I will create a version of `microcircuit.sli` that will allow you to set the number of threads on the command line and also to choose whether to record spikes or not, as well as the size of the network simulated. You could then use a downscaled version (10–20% of the full model) for the single-threaded case and the full model for scaling.

Two more question concerning the SPEC CPU setup: Can you use thread-aware allocators such as jemalloc and can you pin threads to cores? We have seen significant benefits of both in our benchmarks. In one case, we even found that we needed to change BIOS settings to ensure consistent pinning.

**Comment by heshpdx** [comment]
Thanks! I will try this out.  For the verification to be scalable, we will change the output to look like the following (which might require commenting out some of the source):
```
-----------------------------
Simulation report
-----------------------------
Scale            : 0.4
Network size     : 30882
Num connections  : 119605898
Simulated time   : 1000 ms
Total spikes     : 109493
Population spikes: [[10910 8421] [38636 14079] [16251 3848] [7539 9809]], sum: 109493
-----------------------------
```
Basically, cut out any run-specific information such as thread count and time. Then we can diff this output while applying a tolerance to the spike numbers (if we need to).

Would it be easy to do this for hpc_benchmark too? I will take a look tomorrow.

**Comment by heplesser** [comment]
To change the output, you only need to comment out or remove a few lines at the end of the script. The "Population spikes" line is only there as a double-check, "Total spikes" should suffice to check that the simulation is running correctly. "Network size" and "Num connections" depend on scale, but not on the number of threads or on the random seed. For actual benchmark runs, you may want to pass "record=false" as userarg. Then, no spike recorders are created and you will only get the "Total spikes", not the "Population spikes". I just pushed another update to the script so that it, if recording, records always from all neurons, removing a potential source of confusion.

It should be rather straightforward to apply the same user argument handling (at the beginning of the script) and reporting (at the end) to hpc_benchmark. Them main difference is that hpc_benchmark only has two neuron populations, E(xcitatory) and I(nhibitory). Let me know if you run into problems!

**Comment by heshpdx** [comment]
Thank you, this looks good. If I run it multiple times with the same cmdline, I get the same results. When I run it with varying number of threads, the Total spikes and Population spikes aren't exact but they are close. What kind of delta would you expect? Here is some data using ` --userargs=threads=N:scale=.3:seed=108:record=true microcircuit_spec.sli` and varying N. I am just showing the numbers that are changing.
```
N=13, binary built with GCC-12 -O3
    Number of local nodes: 23355
Total spikes     : 83873
Population spikes: [[8740 6585] [29131 10682] [12872 2916] [5495 7452]], sum: 83873
```
```
N=21, with GCC-12 -O3
    Number of local nodes: 23483
Total spikes     : 83266
Population spikes: [[8634 6305] [29095 10586] [12701 2920] [5607 7418]], sum: 83266
```
```
N=21, with LLVM-16 -O3
    Number of local nodes: 23483
Total spikes     : 82910
Population spikes: [[8269 6292] [29086 10566] [12745 2918] [5640 7394]], sum: 82910
```
```
N=28, with GCC-12 -O3
    Number of local nodes: 23483
Total spikes     : 82059
Population spikes: [[8689 6498] [29025 10433] [11816 2892] [5361 7345]], sum: 82059
```
```
N=58, with GCC-12 -O3
    Number of local nodes: 24075
Total spikes     : 84633
Population spikes: [[9307 6772] [28882 10516] [13149 2942] [5525 7540]], sum: 84633
```
```
N=58, with LLVM-16 -O3
    Number of local nodes: 24075
Total spikes     : 83191
Population spikes: [[8575 6375] [29072 10464] [12682 2925] [5609 7489]], sum: 83191
```
```
N=160, with GCC-12 -O3
    Number of local nodes: 25707
Total spikes     : 82472
Population spikes: [[9192 6471] [28472 10390] [12376 2929] [5269 7373]], sum: 82472
```
```
N=160, with LLVM-16 -O3
    Number of local nodes: 25707
Total spikes     : 82667
Population spikes: [[8948 6371] [28917 10423] [12360 2917] [5340 7391]], sum: 82667
```

It appears that the number of local nodes is growing as I add more threading. My machine maxes out with 160 hardware cores, and that shows the most number of local nodes, although the "network size" is invariance across all these runs at 23163. Is this ok? Are any of the output values "out of bounds" in your opinion? It looks like we need a tolerance of about 3% for the spike counts and sum.

Is there a way to output just the "Simulation Report" to a separate file instead of stdout? That way I can also avoid lines like `Number of OpenMP threads: 13` which I would have to mask out. If not, I can hack the source to remove that stanza.

Also, I diffed this script against the microcircuit.sli in your mainline. There are a lot of changes! I'm wondering, could you apply the same kind of changes to hpc_benchmark? Humbly speaking, it would be a lot faster for you to do it correctly than for me to learn it. 

Finally, I have been using BrodyHopfield.sli and brunel_ps.sli as the "test' and "train" workloads which are meant to be very small and kind of small, respectively. Can you help print the same kind of simulation report at the end of those tests to facilitate verification? I tried copying the stanzas from microcircuit.sli, but I am not sure which variables these simulations know about. (alternatively I can scale down microcircuit.sli to also be the test workload, but I would like to have some more code coverage, and not have the "training" workload be exactly the same as the reference benchmark).

Thank you!

**Comment by heplesser** [comment]
- The numbers look good to me and the variation entirely reasonable. 3% is certainly an acceptable tolerance.
- "Network size" counts all neurons (~ 77169 * scale), poisson generators (8) and spike recorders (8). Since the number of neurons is scaled individually for each of the 8 populations, there will be a little bit of round-off from casting doubles to ints, so 23163 is as expected for scale 0.3. This number is invariant under the number of threads.
- "Number of local nodes" also includes the replicas for each poisson generator and spike recorder on each thread, so it should be 2 * 8 * (N-1) larger than "network size" to account for the replicas on threads 1..N-1.
- The report can be written to file. Do you have a preferred naming scheme for the output file?
- Concerning hpc_benchmark, BrodyHopfield and brunel_ps: Do you need all three or would two also do?

**Comment by heshpdx** [comment]
- Thanks for verifying these are ok! 
- Naming scheme for report: doesn't really matter. Perhaps scriptname.sli would output scriptname.rpt ? 
- Other scripts: ideally I would like all three. I've learned from developing other benchmarks for SPEC that there is always a chance that one workload will not work on a platform for an esoteric reason. I like having backup so we are not caught in a hole a few months from now when deadlines are looming.

**Comment by heplesser** [comment]
@heshpdx I have just pushed a new version of `microcircuit_spec.sli` which writes the simulation report to `microcircuit_spec.rpt`. I will look at the other examples later this week. I would suggest not to use BrodyHopfield or brunel_ps. To get different computational loads than with microcircuit, I think hpc_benchmark makes sense (fewer synchronization points than microcircuit due to longer delays) and a model with plastic synapses (more complex memory access patterns due to need to inspect spike history for spike-time dependent plasticity). I will look for a suitable model.

**Comment by heshpdx** [comment]
I pulled your code and started playing around with the scripts. I also see hpc_benchmark and cuba_stdp have spec versions, thank you. I had to make this small change to hpc to avoid a syntax error.
```
diff --git a/examples/nest/hpc_benchmark_spec.sli b/examples/nest/hpc_benchmark_spec.sli
index 68b85e2b3..f2b7b23f7 100644
--- a/examples/nest/hpc_benchmark_spec.sli
+++ b/examples/nest/hpc_benchmark_spec.sli
@@ -342,15 +342,11 @@ RunSimulation
   (Scale            : ) <- scale <- endl
   (Network size     : ) <- ks /network_size get <- endl
   (Num connections  : ) <- ks /num_connections get <- endl
-  (Simulated time   : ) <- t_sim add <- ( ms) <- endl
+  (Simulated time   : ) <- t_sim <- ( ms) <- endl
   (Total spikes     : ) <- ks /local_spike_counter get <- endl
   (Average rate     : ) <- ks /local_spike_counter get cvd NE NI add cvd div t_sim div 1000 mul <- ( sp/s) <- endl
```
I'll try out some values for scale so that the simulation runtime fits within our time and memory budget!

**Comment by heshpdx** [comment]
I played around with microcircuit, cuba_stdp, and hpc_benchmark. The first two are resilient to various system changes and can verify within 3% delta. hpc_benchmark gives a drastically different answer between GCC and LLVM.

I ran the models with 80 threads and a Scale which requires about 15 Gb of memory. About 3 minutes of runtime gives:
```
$ cat gcc-12/hpc_benchmark_spec.rpt
Scale            : 3.2
Network size     : 36001
Num connections  : 405036000
Simulated time   : 4000 ms
Total spikes     : 15322083
Average rate     : 106.403 sp/s
```
```
$  diff gcc-12/hpc_benchmark_spec.rpt llvm-16/hpc_benchmark_spec.rpt
5,6c5,6
< Total spikes     : 15322083
< Average rate     : 106.403 sp/s
---
> Total spikes     : 12307858
> Average rate     : 85.4712 sp/s
```
Do you have insight into why LLVM/clang is so different? We have gone through the source and removed all unstable algorithms and other sources of differences we know of. For example, we replaced std::sort with std::stable_sort, replaced the uniform_distribution/poisson_distribution calls with the LLVM versions as compiled code, and replaced all calls to std::rand with our own "specrand" generator. Usually this does the trick, but there is something else afoot. I would love to get hpc_benchmark working since you mentioned above it is the best one. But I am glad that we have cuba_stdp and microcircuit working at least.

**Comment by heshpdx** [comment]
Another datapoint, from `gcc-12 -Ofast -fno-finite-math-only`. This is good because it tells me it isn't just a gcc vs clang issue. It turns out, gcc-12-Ofast verifies with 80 threads, but when run with 40 threads there are fewer spikes.
```
$ diff gcc-12/hpc_benchmark_spec.rpt gcc-12-Ofast/hpc_benchmark_spec.rpt
5,6c5,6
< Total spikes     : 15322083
< Average rate     : 106.403 sp/s
---
> Total spikes     : 9233948
> Average rate     : 64.1246 sp/s
```

**Comment by heplesser** [comment]
Due to the plasticity in the network, simulations of hpc_benchmark can take very different trajectories, especially if simulated for more than 300 ms. This can lead to wildly differing firing rates, which generally are far higher than biologically plausible rates (around 10 sp/s).

To avoid this problem, I have just pushed a version of hpc_benchmark in which the learning rate is set to zero by default, so that synaptic weights remain constant. The simulation still goes through the mechanics of the spike-time dependent plasticity mechanism, but the dynamics will now stay much more stable. Simulation times should also come down noticeably, since firing rates remain reasonable. Furthermore, variations for different seeds/thread numbers/compilers should now be only a few percent.

The variation in rates which you observed between GCC and Clang and between different thread numbers is most likely due to different random number sequences generated (poisson random variates). To test whether differences you observe between different thread numbers/compilers are reasonable, you should run simulations with five different random seeds and note the variation in spike numbers you get. Changing the number of threads or the compiler should lead to variations in spike numbers comparable to what you see for different seeds.

**Comment by heshpdx** [comment]
Great, thank you. I had increased the simulation time because it seemed that the majority of the runtime was in the setup phase when the network is being constructed (especially for larger Scale networks), and I wanted to make sure we are benchmarking the simulation as well.

**Comment by heshpdx** [comment]
The new hpc script works well. I had to increase tolerance from 3% to 4% to empirically allow results from 160-thread runs that looked ok otherwise. I did notice that the rng_seed value printed in the report is always 1. Maybe it is printing a bool instead of the value?

**Comment by heshpdx** [comment]
My apologies, the seed issue is my own fault! I had changed the source last year when I ingested the code into the harness, to peg all runs with the same seed. Let me think if I want to open that up again, or keep it fixed for all time.

```
void
nest::RandomManager::set_status( const DictionaryDatum& d )
{
  nest_long_t rng_seed;
  bool rng_seed_updated = updateValue< nest_long_t >( d, names::rng_seed, rng_seed );

#ifdef SPEC
  base_seed_ = 1;
#else
  if ( rng_seed_updated )
  {
    if ( not( 0 < rng_seed and rng_seed < ( 1L << 32 ) ) )
    {
      throw BadProperty( "RNG seed must be in (0, 2^32-1)." );
    }

    base_seed_ = static_cast< std::uint32_t >( rng_seed );
  }
#endif
```

**Comment by heplesser** [comment]
I see your point of fixing the seed for consistency in benchmarks. But NEST has a fixed default seed already, see

- https://github.com/nest/nest-simulator/blob/358c7cc3d1897078088abb2c85c436521136d223/nestkernel/random_manager.cpp#L44
- https://github.com/nest/nest-simulator/blob/358c7cc3d1897078088abb2c85c436521136d223/nestkernel/random_manager.cpp#L81

The advantage of a configurable seed is that you can check for the range of variation in simulation results for different random number sequences.

**Comment by heshpdx** [comment]
Yes, I agree. I reverted my change so as to gain the flexibility. Things are running well now. I will let you know how it goes!

**Comment by heplesser** [comment]
@heshpdx Could you contact me by email (hans.ekkehard.plesser@nmbu.no)?

**Comment by heshpdx** [comment]
One of our testers uncovered an issue, only seen on RedHat. Do you have any insight into how to debug this? The connection max in hex is 0x7fffffe so I assume there is some limitation, indicating a runaway model during bring-up phase?

> We are seeing the following error for 867.nest_s when compiled with IC2024.2 compiler on RHEL9 (seems to be passing with the same IC compiler on Ubuntu 22.04). I am wondering if you have any insights to offer as to why this would happen. This was run with –threads 2 and it seems to run for a decent amount of time (~15 mins on EMR/x86) before it fails.
> 
>  
> ```
> # cat microcircuit_spec.sli.out
> 
> NEST 3.7.0-post0.dev0 (C) 2004 The NEST Initiative
> 
> SimulationManager::set_status Info []:
>     Temporal resolution changed from 0.1 to 0.1 ms.
> 
> Connect_g_g_D_D Error []: Too many connections: at most 134217726 connections supported per virtual process and synapse model.
> ```

**Comment by ackurth** [comment]
In principle the error is expected behavior, see [here](https://github.com/nest/nest-simulator/blob/v3.7/nestkernel/connection_manager.cpp#L958). `MAX_LCID=2^27 - 1` is the maximum number of connections per thread and the full-scale microcircuit model has close to 300 million connections.
The error also cannot be due to different random number generators since the connection rule used for the model fixes the total number of connections.
We double checked, and on our systems we are only able to run the full-scale model with at least three threads.

In the model code, the number of connections used for model construction is calculated from pre-defined connection probabilities. This calculation could potentially cause the different behavior, but this seems rather unlikely to me.

Which scale of the model did you use for Ubuntu 22.04 and RHEL8?

**Comment by heshpdx** [comment]
Interesting! We set scale to 1.6 for microcircuit_spec.sli, this way it uses about 24 GB of memory (see graph below from a 40-threaded run, microcircuit is first, and hpc_benchmark is second).  Should we try to increase MAX_LCID? Or do you recommend reducing scale? We do need the ability to run and complete with 1 thread even though it would be ridiculously slow, it is good for proof of scalability.

![image](https://github.com/user-attachments/assets/23b4cf80-a7ef-4787-8f1a-29ec23778121)

**Comment by heshpdx** [comment]
I just found this inside of microcircuit.sli, which explains what you just shared. We will play around with it.



>     Note: Because NEST uses bitfields of limited size in spike communication, only about
>       134 million connections can be handled on a single thread. Therefore, scale
>       must not be larger than 0.4 for a single thread and 0.8 for two threads. If more
>       connections are needed, increase NUM_BITS_LCID in nest_types.h and reduce other
>       NUM_BITS_* correspondingly.

**Comment by ackurth** [comment]
I do not recommend changing the bits, this can lead to unexpected behavior.
In the suggestion above you for example reduce the `NUM_BITS_DELAY`, i.e. the number of bits for the delay in the simulation. It is unclear what consequences this can have on the dynamics.

To proceed I think there are two good options now

1.  use the 0.4 scale network, which can readily be run on 1 thread
2. use some NEST functionality to enable running the a larger scale network on 1 thread already

The first one would be possible right away, for the second one the code would need some minor adaptation.

Do you have a preference?

**Comment by heshpdx** [comment]
Thank you for catching that! We don't actually need to change `NUM_BITS_DELAY`. It is not part of the bits needed for spike communication. That was leftover from my testing, and it accidentally made it in. The other bit adjustments help fix the issue:  whatever problem size we supply needs to run using 1 thread as well as 192 threads. In our case, I reverted back to the prior value for `NUM_BITS_DELAY` and it still gave the same answer. We probably got lucky.

**Comment by heshpdx** [comment]
The committee has been talking recently about memory safety. We ran the small test cases through ARM's MTE and caught an error, and I also used `-fsanitize=hwaddress` to expose issues which mostly uncovered memory leaks. The error is more important than the leaks, but I will share both.

We are running BrodyHopfield.sli single threaded, which is very short but can expose lots of issues:
```
NEST 3.7.0-post0.dev0 (C) 2004 The NEST Initiative

NodeManager::prepare_nodes Info []: 
    Preparing 1003 nodes for simulation.

SimulationManager::start_updating_ Info []: 
    Number of local nodes: 1003
    Simulation time (ms): 600
    Not using OpenMP
    Not using MPI

SimulationManager::run Info []: 
    Simulation finished.
```

First memory error signature is related to the cmdline parsing:
```
(gdb) run BrodyHopfield.sli
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/amptest/specv8/benchspec/CPU/767.nest_r/run/run_base_test_mytest-64.0000/nest_r_base.mytest-64 BrodyHopfield.sli
 
Program received signal SIGSEGV, Segmentation fault
Memory tag violation while accessing address 0x0f0040000021d6c0
Allocation tag 0x0
Logical tag 0xf.
0x000000000040f35c in std::char_traits<char>::compare (__s1=<optimized out>, __s2=<optimized out>, __n=<optimized out>, __s1=<optimized out>,
    __s2=<optimized out>, __n=<optimized out>) at /home/amptest/workspace/speccpu/gcc_tmp/include/c++/14.1.0/bits/char_traits.h:381
381                       return __builtin_memcmp(__s1, __s2, __n);
(gdb) bt
#0  0x000000000040f35c in std::char_traits<char>::compare (__s1=<optimized out>, __s2=<optimized out>, __n=<optimized out>,
    __s1=<optimized out>, __s2=<optimized out>, __n=<optimized out>)
    at /home/amptest/workspace/speccpu/gcc_tmp/include/c++/14.1.0/bits/char_traits.h:381
#1  std::operator==<char, std::char_traits<char>, std::allocator<char> > (__lhs=..., __rhs=<optimized out>, __lhs=..., __rhs=<optimized out>)
    at /home/amptest/workspace/speccpu/gcc_tmp/include/c++/14.1.0/bits/basic_string.h:3776
#2  SLIStartup::SLIStartup (this=0x80040000021aff0, argc=<optimized out>, argv=<optimized out>) at nest-simulator/sli/slistartup.cc:226
#3  neststartup (argc=<synthetic pointer>, argv=<synthetic pointer>, engine=...) at nest-simulator/nest/neststartup.cpp:105
#4  main (argc=<optimized out>, argv=<optimized out>) at nest-simulator/nest/main.cpp:40
```
MTE causes the program to stop immediately, so we don't know what else is behind this issue; it is a onion peeling process. If you have ideas on what to fix, please share.

And then the memory leaks coming out from the hw sanitizer: [BrodyHopfield.sli.err.txt](https://github.com/user-attachments/files/16476315/BrodyHopfield.sli.err.txt)
I ran balancedneuron.sli, and it showed the exact same memory leaks. These are less important than the error but I figured I would share them in case you see something that is very easy to fix. Thanks!

**Comment by heshpdx** [comment]
We were able to clean up the memory safety issue with this patch.
```
--- a/src/nest-simulator/sli/slistartup.cc
+++ b/src/nest-simulator/sli/slistartup.cc
@@ -212,53 +212,55 @@ SLIStartup::SLIStartup( int argc, char** argv )
     StringDatum* sd = new StringDatum( argv[ i ] );
     args_array.push_back( Token( sd ) );
 
-    if ( *sd == "-d" or *sd == "--debug" )
+    std::string myarg = argv[i];
+
+    if ( myarg == "-d" or myarg == "--debug" )
     {
       debug_ = true;
       verbosity_ = SLIInterpreter::M_ALL; // make the interpreter verbose.
       continue;
     }
-    if ( *sd == "--verbosity=ALL" )
+    if ( myarg == "--verbosity=ALL" )
     {
       verbosity_ = SLIInterpreter::M_ALL;
       continue;
     }
-    if ( *sd == "--verbosity=DEBUG" )
+    if ( myarg == "--verbosity=DEBUG" )
...
...
etc
```

**Comment by heplesser** [comment]
@heshpdx Great that you found a fix for the memory leaks—does the change you sketched fix all the leaks reported? Could you create a pull request against NEST master for this fix?

I have just pushed to my `fix-3217-spec` branch a version of the microcircuit benchmark that writes connection numbers to a separate log file for each `Connect` call. The script is `microcircuit_spec_cdb.sli` and the extra log file is `conn_debug.log`.  Could you ask your colleagues to run this script on RHEL9 and Ubuntu 22.04 and send me the resulting logs? For scale 1.6 and 2 threads (or, to save time, scale 1 and 1 thread), this code should fail with the "max 134 million synapses" error, so it is surprising and disconcerting that the code passed under Ubuntu

**Comment by heshpdx** [comment]
That patch didn't fix the leaks, it was a fix for the memory safety error. I think the `StringDatum` stuff has its own type of memory management which didn't play well with the cmdline parsing.

I did look at the first/biggest leak (since they are ordered by size), and the fix is like this:
```
--- a/src/nest-simulator/sli/parser.h
+++ b/src/nest-simulator/sli/parser.h
@@ -38,7 +38,7 @@
 
 class Parser
 {
-  Scanner* s;
+  Scanner* s = nullptr;
 
   Token arraytoken;
   Token proctoken;
@@ -61,6 +61,7 @@ class Parser
 public:
   Parser();
   Parser( std::istream& );
+  ~Parser() { if (s) delete s; }
 
   bool operator()( Token& );
```
But we don't care so much about the leaks since the operating system will clean them up (I won't be looking further, but I imagine will all be similar).

For the connection issue, I was able to reproduce the RHEL behavior on Ubuntu. It had nothing to do with OS; I just initially thought it did but we root-caused it to running with just a single thread. The fix was to adjust `NUM_BITS_RANK`, `NUM_BITS_SYN_ID`, and `NUM_BITS_LCID` to accommodate one thread as well as many threads.

**Comment by heplesser** [comment]
@heshpdx Thank you for the update. It is good to know that the difference between RHEL and Ubuntu was due to a different number of threads.

I will create a separate issue for the memory leaks. They seem mostly related to the SLI parser, not the NEST kernel and should thus not affect results.

**Comment by heshpdx** [comment]
Thank you for helping me with #3304 and #3305. I did not expect to become a NEST developer, but here we are 😄

**Comment by heshpdx** [comment]
We have been using `BrodyHopfield.sli` as the short/simple test. We noticed that it does not consume the `--userargs=threads=N`  directive on the command line, and just spawns as many threads as the system can handle. Is there an easy patch we can apply to have the thread count limited?

**Comment by heshpdx** [comment]
We have made a lot of progress, and the NEST candidate has moved forward to the next step. We are testing on a wide variety of systems, and there is one that is livelocking during a multithreaded run. The particular system has an HP Cray Compiler 18 running on an AMD EPYC with linux. Building with this compiler, the nest cmdline runs forever until we kill it (the expected runtime is around 3 minutes). I asked them to run in gdb and get a stack trace of where it is stuck, and they sent this over. This is running `microcircuit.sli`; it seems to get hung right at the start of execution.

```
(gdb) bt
#0  0x000014c204df2ed3 in __cray$mt_set_lock ()
   from /opt/cray/pe/cce/18.0.1/cce/x86_64/lib/libcraymp.so.2
#1  0x000014c204dbabe3 in __kmpc_critical ()
   from /opt/cray/pe/cce/18.0.1/cce/x86_64/lib/libcraymp.so.2
#2  0x0000000000aa8f38 in SLIInterpreter::message (this=0x7ffeb179d7c0, level=10,
    from=0xe52f30 "SimulationManager::set_status",
    text=0xdeace0 "Temporal resolution changed from 0.1 to 0.1 ms.", errorname=0x20b1cc "")
    at nest-simulator/sli/interpret.cc:778
#3  0x0000000000982a15 in nest::LoggingManager::deliver_logging_event_ (this=<optimized out>,
    event=...) at nest-simulator/nestkernel/logging_manager.cpp:88
#4  nest::LoggingManager::publish_log (this=<optimized out>, s=<optimized out>, fctn=...,
    msg="Temporal resolution changed from 0.1 to 0.1 ms.", file=..., line=301)
    at nest-simulator/nestkernel/logging_manager.cpp:121
#5  0x0000000000a61f69 in nest::SimulationManager::set_status (this=0xca8728, d=...)
    at nest-simulator/nestkernel/simulation_manager.cpp:301
#6  0x000000000092fcac in nest::KernelManager::set_status (this=<optimized out>, dict=...)
    at nest-simulator/nestkernel/kernel_manager.cpp:174
#7  0x000000000099446b in nest::set_kernel_status (dict=...)
    at nest-simulator/nestkernel/nest.cpp:105
#8  0x00000000009a885f in nest::NestModule::SetKernelStatus_DFunction::execute (
    this=<optimized out>, i=0x7ffeb179d7c0) at nest-simulator/nestkernel/nestmodule.cpp:342
#9  0x0000000000ab9373 in FunctionDatum::execute (this=0xb9aad0, i=0x7ffeb179d7c0)
    at nest-simulator/sli/functiondatum.h:114
#10 0x0000000000ab6841 in SLIInterpreter::execute_ (this=this@entry=0x7ffeb179d7c0,
    exitlevel=exitlevel@entry=0) at nest-simulator/sli/interpret.cc:1330
#11 0x0000000000ab7bbe in SLIInterpreter::execute (this=0x7ffeb179d7c0, v=0)
    at nest-simulator/sli/interpret.cc:1253
#12 0x000000000036779c in main (argc=3, argv=0x7ffeb179da68) at nest-simulator/nest/main.cpp:43
 ```

Along with a note:

> There seem to be nested “omp critical” pragmas. There’s one at line 119 of nest-simulator/nestkernel/logging_manager.cpp (4 in the backtrace) and then another one at line 778 of nest-simulator/sli/interpret.cc (2 in the backtrace – essentially where it gets stuck). That’s supposed to be permitted (as the two critical regions have different names), but I’m not sure it’s a good idea).

I've asked them to turn off logging using `--verbosity=QUIET` just to see if that would allow forward progress. If you have more ideas, please share. Thank you!

**Comment by heshpdx** [comment]
Turning off logging didn't help Cray, but disabling the critical region at sli/interpret.cc:778 did fix their deadlock. Do you have any insight into whether or not that region needs to be critical considering that nestkernel/logging_manager.cpp:121 is already critical?

**Comment by heplesser** [comment]
Hi @heshpdx! See https://github.com/nest/nest-simulator/pull/3420 for a solution (fingers crossed).

**Comment by bowers** [comment]
I work with @heshpdx on the SPEC committee.  One problem I've had is that including "--userargs=blah=blah" on the command line was causing an infinite loop in Windows.  I've tracked the problem down to 

https://github.com/nest/nest-simulator/blob/b70d597c727b4ae48735d8a6f1fb13664e1d2ff8/sli/slidata.cc#L1446C2-L1446C66

On Windows, the constant needs to be ULLONG_MAX. So something like:
```
#if defined(_WIN32)
  if ( p == ULLONG_MAX )
#else
  if ( p == ULONG_MAX )
#endif
```

**Comment by heplesser** [comment]
@bowers I just created #3423 which should fix this problem in an entirely general way. You hit part of our code here that probably hasn't seen anything but formatting changes since the days of gcc 2.91 :).

**Comment by heshpdx** [comment]
Thank you for these two patches! I have incorporated them both and confirm that they address the respective issues on HPE Cray and MSVC.

**Comment by bowers** [comment]
I am debugging an unexpected exit when running a particular SLI file on a Windows platform, with mingw-w64 (gcc13).
The simulator ends with an EXITCODE_SCRIPTERROR. I've isolated the error to this line in the SLI file:
`0.05 (inf) cvd redraw`
Under the debugger, I can see that when the redraw function is called (specifically RedrawParameter::RedrawParameter), the min parameter is 0.05, but the max parameter is 0 (instead of inf).  One of the RedrawParameter() checks (below) thus throws the error.
```
  if ( min > max )
  {
    throw BadParameterValue( "min <= max required." );
  }

```
I will continue to search for the underlying problem, so just FYI for now. I suspect some weird local definition of INFINITY, or an unexpected double-to-something-else conversion.  It could also be something unique to my specific installation of mingw-w64 + gcc.

**Comment by heplesser** [comment]
@bowers Thanks for reporting this. I assume you hit this problem here: https://github.com/nest/nest-simulator/blob/09b349c55298d346e8aceea4f0ae643dea8ee7a3/examples/nest/Potjans_2014/microcircuit.sli#L438

The problem most likely originates here: https://github.com/nest/nest-simulator/blob/09b349c55298d346e8aceea4f0ae643dea8ee7a3/sli/slidata.cc#L1386

Could you check what `std::atof( "inf" )` returns on your MinGW system?

**Comment by bowers** [comment]
In fact, I'd also narrowed it down to that spot.  atof("inf") returns 0 on MinGW.  (It also returns 0 running Ubuntu on WSL.)  However, strtod("inf") returns inf.  So the patch below works on MinGW (compiling with /DSPEC_FIX):

```
#if defined(SPEC_FIX)
  Token t( new DoubleDatum( std::strtod( obj->c_str() , NULL) ) );  
#else  
  Token t( new DoubleDatum( std::atof( obj->c_str() ) ) );
#endif

```

I have yet to try the above with on a real Linux system, and with other compilers.  I'm also not sure what the C++ standards say should happen when "inf" is given as an input for either atof() or strtod(). So I'm not ready to suggest a PR. But very pleased to locate my issue, so thank you.

**Comment by heplesser** [comment]
@bowers A PR would be excellent. There is no need for keeping the old `atof()` around, so replacing the existing line with

```c++
Token t( new DoubleDatum( std::strtod( obj->c_str(), nullptr ) ) ); 
```

would be all it takes.

**Comment by heshpdx** [comment]
We ran with ubsan, the undefined behavior sanitizer in LLVM, and it picked up the following error where it looks like we are trying to dereference page 0x0.

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1419337==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000001 (pc 0x7f3e2e348dbe bp 0x7ffff3daf880 sp 0x7ffff3daf4b0 T0)
==1419337==The signal is caused by a READ memory access.
==1419337==Hint: address points to the zero page.
    #0 0x7f3e2e348dbe in __dynamic_cast (/spec/compilers/llvm-20.1.0/lib/x86_64-unknown-linux-gnu/libc++abi.so.1+0x3fdbe)
    #1 0x558366ac2a8e in RollFunction::execute(SLIInterpreter*) const /spec/cpuv8/cpuv8-0.75.0/root-drm-7552-llvm20/benchspec/CPU/767.nest_r/build/build_base_drm-llvm-20.1.0-64-sanitize_address_undefined.0000/nest-simulator/sli/slistack.cc:279:27
    #2 0x55836698f0ab in FunctionDatum::execute(SLIInterpreter*) /spec/cpuv8/cpuv8-0.75.0/root-drm-7552-llvm20/benchspec/CPU/767.nest_r/build/build_base_drm-llvm-20.1.0-64-sanitize_address_undefined.0000/nest-simulator/sli/functiondatum.h:114:13
    #3 0x5583669870a9 in SLIInterpreter::execute_(unsigned long) /spec/cpuv8/cpuv8-0.75.0/root-drm-7552-llvm20/benchspec/CPU/767.nest_r/build/build_base_drm-llvm-20.1.0-64-sanitize_address_undefined.0000/nest-simulator/sli/interpret.cc:1323:25
    #4 0x558366986aad in SLIInterpreter::startup() /spec/cpuv8/cpuv8-0.75.0/root-drm-7552-llvm20/benchspec/CPU/767.nest_r/build/build_base_drm-llvm-20.1.0-64-sanitize_address_undefined.0000/nest-simulator/sli/interpret.cc:1203:16
    #5 0x558366255d57 in neststartup(int*, char***, SLIInterpreter&) /spec/cpuv8/cpuv8-0.75.0/root-drm-7552-llvm20/benchspec/CPU/767.nest_r/build/build_base_drm-llvm-20.1.0-64-sanitize_address_undefined.0000/nest-simulator/nest/neststartup.cpp:122:17
    #6 0x5583658c2cba in main /spec/cpuv8/cpuv8-0.75.0/root-drm-7552-llvm20/benchspec/CPU/767.nest_r/build/build_base_drm-llvm-20.1.0-64-sanitize_address_undefined.0000/nest-simulator/nest/main.cpp:40:3
    #7 0x7f3e2dfd3d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

==1419337==Register values:
rax = 0xffffffffffefffff  rbx = 0x0000558366b4aa30  rcx = 0x0000000000000000  rdx = 0x00007f3e2e34ff88  
rdi = 0x0000000000000001  rsi = 0x00007f3e2e34ff30  rbp = 0x00007ffff3daf880  rsp = 0x00007ffff3daf4b0  
 r8 = 0x00007cee2d3e0101   r9 = 0x0000000000000000  r10 = 0x00007f3e2e34ff01  r11 = 0x0000000000000246  
r12 = 0x0000558367db38d0  r13 = 0xa2c0efc0f49b3d4f  r14 = 0x0000000000000000  r15 = 0x0000000000000000  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/spec/compilers/llvm-20.1.0/lib/x86_64-unknown-linux-gnu/libc++abi.so.1+0x3fdbe) in __dynamic_cast
==1419337==ABORTING
```

It happens right at the end of `RollFunction::execute`
https://github.com/nest/nest-simulator/blob/d1ff1b1dcdc2a1217fe69617d5e72dc63fe196ae/sli/slistack.cc#L279

The header comment indicates that if we underflow the stack then an exception is raised. But in our case, that never happens. Here is the code coverage of that function which is executed 4085 times -- this is with a successful run with the sanitizer turned off. (Also, a `nest_long_t` is just typedef'd to `long` in linux.)

![Image](https://github.com/user-attachments/assets/93ec56d9-87a8-4ba0-a940-8110614b8091)

Do you have any insight into this one? This file hasn't changed in 3 years!

FYI, the sanitizer build is done with these flags:
```
llvm-20.1.0/bin/clang++ -std=c++17 -m64 -stdlib=libc++ -g -O3 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address,undefined -fsanitize=float-divide-by-zero,unsigned-integer-overflow,implicit-conversion,local-bounds  -fno-sanitize-recover=undefined -fsanitize-recover=float-divide-by-zero -fsanitize-address-use-after-return=always -fsanitize-address-use-after-scope  
```

**Comment by heplesser** [comment]
@heshpdx I have just created PR #3460 which addresses already a number of problems raised by the sanitizers. Could you give it a try? I am still investigating some additional issues. Could you run the actual benchmark scripts with the sanitizer-equipped code to see if that turns up any more problems?

**Comment by heplesser** [comment]
> [@heshpdx](https://github.com/heshpdx) I have just created PR [#3460](https://github.com/nest/nest-simulator/pull/3460) which addresses already a number of problems raised by the sanitizers. Could you give it a try? I am still investigating some additional issues. Could you run the actual benchmark scripts with the sanitizer-equipped code to see if that turns up any more problems?

I have now solved remaining issues and gotten almost the entire test suite to run through (some tests are difficult to run with the sanitizers in place due to library loading order issues).

**Comment by heshpdx** [comment]
I confirm now that the undefined behavior sanitizer is clean! Thank you!

**Comment by bowers** [comment]
Thanks, @heplesser. This helps. 

We are considering deactivating netshutdown() to avoid this slowdown. We've tried that, and it does work fine. I'm continuing to profile / trace to figure out the root cause, because regardless of what SPEC does, this looks interesting.  Among other things that I intend to try are running with jemalloc.

I'm running multiple systems, including Windows Server 2019 + MSVC 19 (both on x86 and aarch64), and Windows Server 2019 + MinGW/gcc 13.  (I haven't run this on WSL, because my personal WSL-configured PC doesn't have enough memory to run our multithreaded workload, but I'll try to find a box to try because that might yield a clue.)

**Comment by heplesser** [comment]
NEST is now part of the SPEC CPU 2026 industry benchmark: https://www.spec.org/cpu2026/docs/overview.html#Q13

- SPECrate®2026 Floating Point: `nest.767_r`
- SPECspeed®2026 Floating Point: `nest.867_s`

There is also a paper on SPEC CPU 2026:

Madhav, M., Lee, A., Mejia, A., Moore, B., Soppadandi, C., Cambly, C., Müllner, C., Bowers, D., Reiner, D., Bakhvalov, D., Zhao, D., Voth, D., Xue, F., Silber-Chaussumier, F., Bucek, J., Southern, J., Liu, J., Himer, J., Henning, J., … Todorovski, Z. (2026). 
SPEC CPU: The Next Generation (Version 1). 
arXiv. https://doi.org/10.48550/ARXIV.2605.01575

Therefore closing this issue as completed :).
