### ISSUE TITLE
Ensure all examples work with 2.12 and avoid deprecated functions

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#558]
Once all other issues for this milestone are complete, including #552, ensure that all examples work and do not use deprecated functionality.

**Comment by heplesser** [comment]
Any issues arising here are fixed in #580.

**Comment by Silmathoron** [comment]
There are some subtle problems remaining concerning deprecation matters.
For instance ``iaf_neuron`` is still present in many docstrings' examples:

- pynest/nest/lib/hl_api_models.py
- models/volume_transmitter.h
- models/stdp_dopa_connection.h
- topology/topologymodule.cpp
- nestkernel/nestmodule.cpp
- models/music_event_in_proxy.h
- models/music_event_out_proxy.h
- nestkernel/nestmodule.h
- lib/sli/nest-init.sli
- models/iaf_psc_delta.h
- models/pp_psc_delta.h
- nestkernel/model_manager.h
- sli/slidict.cc
- nestkernel/node.h
- topology/pynest/hl_api.py

Also in some documentation/examples code:

- doc/nest_by_example/scripts/one_neuron_with_sine_wave.py
- doc/model_details/noise_generator.ipynb
- extras/userdoc/md/documentation/*
- extras/ConnPlotter/examples/*
- examples/nest/*.sli
- examples/nest/music/*
- examples/neuronview/neuronview.py
- topology/doc/user_manual_scripts/*
- doc/conngen/conngen.txt

Eventually, there was a mistake in #580 as [``iaf_neuron`` is said to be replaced by ``iaf_cond_alpha`` instead of ``iaf_psc_alpha``](https://github.com/nest/nest-simulator/blob/master/pynest/nest/lib/hl_api_helper.py#L417).
